### ISSUE TITLE
issue-5-search-for-entry

### ISSUE THREAD

**Issue by jsygo** [jsygo/code-journal#10]
## 💰 Motivation

User may need to search their entries. 

## 📐 Plan

Provide a search box that causes the entries list to only show matches.

## ✅ Task List

- [x] Add a search bar right below the heading for the entries list
- [x] Add an `input` event listener to the search bar
- [x] Use a loop to check if entries match the content of the search bar
  - [x] If they don't match, make sure they do not display
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
